# Generated by Django 4.2.7 on 2023-11-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estacionamieto', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('capacidad', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
